### ISSUE TITLE
Win10版闪退的临时解决办法

### ISSUE THREAD

**Issue by lexjhuang** [getlantern/lantern-forum-cn#301]
今天我的付费版突然闪退，经过一段调试后我写了一个bat脚本内容如下，之后我的付费版就可以正常启动了，希望这个对你们团队以及其他人有帮助！

del C:\Users\Administrator\AppData\Roaming\Lantern\global.yaml
Start C:\Users\Administrator\AppData\Roaming\Lantern\lantern.exe

**Comment by poppyccc** [comment]
非常感谢！按照你的脚本，终于解决了闪退的问题，可以正常使用啦

**Comment by Letitebe19831018** [comment]
非常感谢！按照你的脚本，终于解决了闪退的问题，可以正常使用啦

**Comment by wuchunhua512** [comment]
@lexjhuang 你好，请问下Mac系统上的蓝灯也突然闪退是什么问题？

**Comment by wuchunhua512** [comment]
找到文件了！
Mac的蓝灯删除问题处理方案：
删除 /Users/xxxx(这里是你Mac的用户名)/Library/Application Support/Lantern/global.yaml
重新启动，然后重新授权即可

**Comment by HaleChu** [comment]
感谢，删除global.yaml后重启蓝灯不会闪退可以正常使用。只不过需要重新授权

**Comment by lexjhuang** [comment]
蓝灯7.8.3已经解决闪退问题，所以关闭这个issue
