### ISSUE TITLE
cannot add a new device on Lantern Pro

### ISSUE THREAD

**Issue by ttcath** [getlantern/lantern-forum-cn#6]
On Lantern 7.3.6 (20230224.141941) for Windows , and  7.3.2 (20230218.180638) for android. When I willing to authorize a new device by use authorized code, but on new device, there is no place to appear the code, so that i could not finished the progress.

@myleshorton pls ask your team in case to fix the problem.

Following logs for reference at 

https://lantern.jitbit.com/helpdesk/Ticket/57643525
https://lantern.jitbit.com/helpdesk/Ticket/57643483

**Comment by myleshorton** [comment]
Which is the new device you're trying to add? Windows or Android?

**Comment by oxtoacart** [comment]
I just tested this with 7.3.6 on a Mac and it seems to work. @ttcath can you please describe the exact steps that you are taking and include screenshots?

Thanks!

**Comment by ttcath** [comment]
Dear @oxtoacart 

Please find the screeshot, I get this at Windows by using the two PC based on windows.

Once I want to link PC1 to PC2 on 7.3.6 on Windows, the link to device page shows same, on PC2 (which will be linked to PC1, no code on the page)


![image](https://user-images.githubusercontent.com/60735821/228285263-99c490ec-8b9a-4d36-9867-f68abdcc25f1.png)

**Comment by oxtoacart** [comment]
@ttcath the screenshot you shared is for a PC that is already linked to your Pro account. Do you have a screenshot from the PC that is not yet Pro?

**Comment by ttcath** [comment]
nope. @oxtoacart 

Step I reinstall Chorme Broswer on PC 1( Lantern Pro linked) 
step 2: remove PC 2 which authorized to use Lantern Pro
Step 3: install Lantern Pro on PC2 by using same account
Step 4: Add device on PC1, the screen shows above.
Step 5: Try to add PC2 by using code, not work. (The device list shows 1 Android Phone, 1 Windows 10 PC)

**Comment by oxtoacart** [comment]
@ttcath I'm sorry, I still don't understand what exactly you see. After step 3, do you open the device linking screen on PC2 to get the code? Does it not show you the code, or do you try putting the code into PC1 and it rejects the code?

**Comment by ttcath** [comment]
Dear @oxtoacart 

Yes!
After Step 3, I open PC 2, in case to get code from PC1, but on PC1, the screen shows above. Also, on my Android Phone, if I want to generate code for adding new device, it also shows like screenshot shows above.
Currently, I only link 1 PC1, 1 HUAWEI PHONE, nothing more.

**Comment by ttcath** [comment]
Dear @myleshorton 
for logs on phone, pls cf. https://lantern.jitbit.com/helpdesk/Ticket/57643525
for logs on windows, pls cf. https://lantern.jitbit.com/helpdesk/Ticket/57643483

**Comment by ttcath** [comment]
Dear @myleshorton @oxtoacart 

I solved this matter by myself, thus,
Step 1: uninstall the APP at all devices
Step 2: install the APP on ABR-AL80, get the activation code from PC
step 3: install the APP on HRY-AL00T, get the activation code from ABR-AL80
Step 4: open the software on PC, check the devices status

Problem is: get the activation code at  ABR-AL80 and HRY-AL00T by using WLAN, cannot do so, but if i use roaming or the WLAN provided by Roaming WLAN, that will be done.
